// <auto-generated />
namespace MovieCinemas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddClubCardsModelAndAddAdministratorFKToTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClubCardsModelAndAddAdministratorFKToTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202109241447516_AddClubCardsModelAndAddAdministratorFKToTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
